
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENUP = 9;
  public static final int IDD = 31;
  public static final int MULTIPLICACION = 23;
  public static final int GUION = 21;
  public static final int PARENTESIS_ABIERTO = 25;
  public static final int IGUAL = 27;
  public static final int RIGHTT = 6;
  public static final int POSITIONXY = 13;
  public static final int DIVISION = 24;
  public static final int SUMA = 22;
  public static final int CORCHETE_CERRADO = 29;
  public static final int TOCENTER = 11;
  public static final int COLOR = 12;
  public static final int POSITIONY = 15;
  public static final int POSITIONX = 14;
  public static final int BACKWARD = 5;
  public static final int PARENTESIS_CERRADO = 26;
  public static final int FORWARD = 4;
  public static final int COMA = 30;
  public static final int PENDOWN = 10;
  public static final int NUMEROS = 33;
  public static final int EOF = 0;
  public static final int SHOWTURTLE = 17;
  public static final int TODRAW = 19;
  public static final int TOERASE = 18;
  public static final int LEFTT = 7;
  public static final int error = 1;
  public static final int HIDETURTLE = 16;
  public static final int CLEARS = 8;
  public static final int COMENTARIO = 32;
  public static final int HEXADECIMAL = 2;
  public static final int CORCHETE_ABIERTO = 28;
  public static final int REPEAT = 20;
  public static final int NUMERAL = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEXADECIMAL",
  "NUMERAL",
  "FORWARD",
  "BACKWARD",
  "RIGHTT",
  "LEFTT",
  "CLEARS",
  "PENUP",
  "PENDOWN",
  "TOCENTER",
  "COLOR",
  "POSITIONXY",
  "POSITIONX",
  "POSITIONY",
  "HIDETURTLE",
  "SHOWTURTLE",
  "TOERASE",
  "TODRAW",
  "REPEAT",
  "GUION",
  "SUMA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "IGUAL",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "COMA",
  "IDD",
  "COMENTARIO",
  "NUMEROS"
  };
}

